import { StyleSheet, Dimensions, Platform } from "react-native";
import { Colors } from "../constants/Colors";

const { width, height } = Dimensions.get("window");
export const SIDEBAR_WIDTH = width * 0.8;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.dark.background,
    },
    topBar: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingTop: Platform.OS === "ios" ? 60 : 40,
        paddingHorizontal: 20,
        paddingBottom: 10,
    },
    topBarIcon: {
        width: 44,
        height: 44,
        borderRadius: 14,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 10,
    },
    topBarIconSmall: {
        width: 38,
        height: 38,
        borderRadius: 12,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 10,
    },
    topBarRight: {
        flexDirection: "row",
    },

    mainContent: {
        flex: 1,
        paddingHorizontal: 20,
    },
    zikirDisplay: {
        position: "absolute",
        top: 5,
        left: 20,
        right: 20,
        backgroundColor: "rgba(30, 41, 59, 0.7)",
        borderRadius: 24,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.1)",
        zIndex: 20,
        overflow: "hidden",
    },
    zikirDisplayExpanded: {
        backgroundColor: "rgba(15, 23, 42, 0.95)",
        borderColor: Colors.dark.primary,
    },
    zikirContentContainer: {
        padding: 16,
        alignItems: "center",
    },
    arabicTextDisplay: {
        fontSize: 28,
        color: Colors.dark.primary,
        textAlign: "center",
        fontFamily: Platform.OS === "ios" ? "Traditional Arabic" : "serif",
        lineHeight: 40,
        marginBottom: 4,
    },
    zikirTextDisplay: {
        fontSize: 16,
        fontWeight: "700",
        color: Colors.dark.text,
        textAlign: "center",
        letterSpacing: 0.5,
        marginBottom: 12,
    },
    progressContainer: {
        width: "100%",
        height: 4,
        marginTop: 4,
    },
    expandHint: {
        position: "absolute",
        bottom: 2,
        alignItems: "center",
        justifyContent: "center",
    },
    progressTrack: {
        width: "100%",
        height: "100%",
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        borderRadius: 2,
        overflow: "hidden",
    },
    progressActive: {
        height: "100%",
        backgroundColor: Colors.dark.primary,
        borderRadius: 2,
    },
    counterSection: {
        ...StyleSheet.absoluteFillObject,
        alignItems: "center",
        justifyContent: "center",
        paddingTop: height * 0.18,
    },
    touchArea: {
        width: width,
        height: width * 0.85,
        alignItems: "center",
        justifyContent: "center",
    },
    outerCircle: {
        width: width * 0.7,
        height: width * 0.7,
        borderRadius: (width * 0.7) / 2,
        backgroundColor: "transparent",
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 8,
        borderColor: Colors.dark.primary,
        shadowColor: Colors.dark.primary,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    innerCircle: {
        width: width * 0.62,
        height: width * 0.62,
        borderRadius: (width * 0.62) / 2,
        backgroundColor: "#0F172A",
        alignItems: "center",
        justifyContent: "center",
    },
    circleFinished: {
        backgroundColor: "rgba(16, 185, 129, 0.02)",
        borderColor: "#10B981",
        shadowColor: "#10B981",
        shadowOpacity: 0.8,
        shadowRadius: 40,
        elevation: 20,
    },
    finishedGlow: {
        position: "absolute",
        width: width * 0.72,
        height: width * 0.72,
        borderRadius: (width * 0.72) / 2,
        borderWidth: 1.5,
        borderColor: "rgba(16, 185, 129, 0.4)",
    },
    innerCircleFinished: {
        backgroundColor: "#0F172A",
        borderWidth: 1,
        borderColor: "rgba(16, 185, 129, 0.15)",
    },
    finishedContent: {
        alignItems: "center",
        justifyContent: "center",
    },
    targetReachedText: {
        fontSize: 10,
        fontWeight: "900",
        color: "#10B981",
        letterSpacing: 4,
        marginTop: 8,
        opacity: 0.9,
    },
    mainCount: {
        fontSize: 110,
        fontWeight: "900",
        color: Colors.dark.text,
        includeFontPadding: false,
    },
    targetCount: {
        fontSize: 24,
        fontWeight: "700",
        color: Colors.dark.textSecondary,
        marginTop: -5,
    },
    mainCountFinished: {
        fontSize: 85,
        fontWeight: "900",
        color: "#F8FAFC",
        textShadowColor: "rgba(16, 185, 129, 0.6)",
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 15,
    },

    // Sidebar Styles
    overlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: "rgba(0, 0, 0, 0.7)",
        zIndex: 100,
    },
    overlayPressable: {
        flex: 1,
    },
    sidebar: {
        position: "absolute",
        left: 0,
        top: 0,
        bottom: 0,
        width: width * 0.8,
        backgroundColor: "#0F172A",
        zIndex: 101,
        borderRightWidth: 1,
        borderRightColor: "rgba(255, 255, 255, 0.05)",
        shadowColor: "#000",
        shadowOffset: { width: 4, height: 0 },
        shadowOpacity: 0.5,
        shadowRadius: 20,
        elevation: 25,
        paddingTop: Platform.OS === "ios" ? 60 : 40,
    },
    sidebarHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 24,
        marginBottom: 40,
    },
    sidebarTitleMain: {
        fontSize: 24,
        fontWeight: "900",
        color: "#F8FAFC",
        letterSpacing: 1,
    },
    titleUnderline: {
        width: 30,
        height: 4,
        backgroundColor: Colors.dark.primary,
        marginTop: 4,
        borderRadius: 2,
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        alignItems: "center",
        justifyContent: "center",
    },
    sidebarContent: {
        flex: 1,
        paddingHorizontal: 16,
    },
    sidebarItem: {
        flexDirection: "row",
        alignItems: "center",
        padding: 14,
        borderRadius: 16,
        marginBottom: 8,
        backgroundColor: "transparent",
    },
    sidebarItemPressed: {
        backgroundColor: "rgba(255, 255, 255, 0.05)",
    },
    sidebarIconWrapper: {
        width: 42,
        height: 42,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 16,
    },
    sidebarItemText: {
        fontSize: 16,
        fontWeight: "700",
        color: "#E2E8F0",
    },
    sidebarIconPurple: {
        width: 42,
        height: 42,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 16,
        backgroundColor: "rgba(139, 92, 246, 0.1)",
    },
    sidebarIconYellow: {
        width: 42,
        height: 42,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 16,
        backgroundColor: "rgba(234, 179, 8, 0.1)",
    },
    sidebarIconTeal: {
        width: 42,
        height: 42,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 16,
        backgroundColor: "rgba(20, 184, 166, 0.1)",
    },
    sidebarIconIndigo: {
        width: 42,
        height: 42,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 16,
        backgroundColor: "rgba(99, 102, 241, 0.1)",
    },
    sidebarIconBlue: {
        width: 42,
        height: 42,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 16,
        backgroundColor: "rgba(59, 130, 246, 0.1)",
    },
    sidebarDivider: {
        height: 1,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        marginVertical: 20,
        marginHorizontal: 12,
    },
    sidebarFooter: {
        padding: 30,
        alignItems: "center",
        borderTopWidth: 1,
        borderTopColor: "rgba(255, 255, 255, 0.05)",
    },
    versionText: {
        color: "rgba(255, 255, 255, 0.2)",
        fontSize: 12,
        fontWeight: "400",
        letterSpacing: 2,
    },

    // Reminder Modal Styles
    modalOverlay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0, 0, 0, 0.7)",
    },
    modalBg: {
        ...StyleSheet.absoluteFillObject,
    },
    reminderCard: {
        width: width * 0.85,
        backgroundColor: "#1E293B",
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.1)",
    },
    reminderHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    reminderTitle: {
        fontSize: 20,
        fontWeight: "800",
        color: Colors.dark.text,
    },
    reminderContent: {
        marginBottom: 24,
    },
    reminderRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    reminderLabel: {
        fontSize: 16,
        fontWeight: "600",
        color: Colors.dark.text,
        marginBottom: 4,
    },
    reminderSubLabel: {
        fontSize: 12,
        color: Colors.dark.textSecondary,
        width: width * 0.5,
    },
    timeSelectBox: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "rgba(234, 179, 8, 0.05)",
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(234, 179, 8, 0.2)",
    },
    timeLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: Colors.dark.textSecondary,
    },
    timeDisplay: {
        flexDirection: "row",
        alignItems: "center",
    },
    timeValue: {
        fontSize: 18,
        fontWeight: "800",
        color: Colors.dark.primary,
        marginRight: 6,
    },
    doneButton: {
        backgroundColor: Colors.dark.primary,
        paddingVertical: 14,
        borderRadius: 14,
        alignItems: "center",
    },
    doneButtonText: {
        color: "#0F172A",
        fontSize: 16,
        fontWeight: "700",
    },
    sectionHeader: {
        color: Colors.dark.primary,
        fontSize: 12,
        fontWeight: "800",
        letterSpacing: 2,
        marginBottom: 20,
    },
    langGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        rowGap: 10,
    },
    langItem: {
        width: "48%", // Allow 2 columns
        paddingHorizontal: 12,
        paddingVertical: 12,
        borderRadius: 12,
        backgroundColor: "#1F2937",
        alignItems: "center",
        justifyContent: "flex-start",
        borderWidth: 1,
        borderColor: "#374151",
        flexDirection: "row",
        gap: 10,
    },
    langItemActive: {
        backgroundColor: "#8B5CF615",
        borderColor: "#8B5CF6",
    },
    langFlag: {
        fontSize: 18,
    },
    langLabel: {
        color: "#9CA3AF",
        fontSize: 14,
        fontWeight: "500",
    },
    langLabelActive: {
        color: "#8B5CF6",
        fontWeight: "700",
    },
});
