import { StyleSheet, Dimensions } from "react-native";
import { Colors } from "../constants/Colors";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.dark.background,
    },
    content: {
        padding: 20,
        paddingBottom: 40,
    },
    summaryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 24,
    },
    summaryCard: {
        backgroundColor: Colors.dark.surface,
        borderRadius: 20,
        padding: 20,
        width: (width - 55) / 2,
        borderWidth: 1,
        borderColor: Colors.dark.border,
    },
    iconBox: {
        width: 44,
        height: 44,
        borderRadius: 12,
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 16,
    },
    summaryValue: {
        color: Colors.dark.text,
        fontSize: 24,
        fontWeight: "800",
        marginBottom: 4,
    },
    summaryLabel: {
        color: Colors.dark.textSecondary,
        fontSize: 12,
        fontWeight: "500",
    },
    chartSection: {
        backgroundColor: Colors.dark.surface,
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: Colors.dark.border,
        marginBottom: 24,
    },
    sectionTitle: {
        color: Colors.dark.text,
        fontSize: 16,
        fontWeight: "700",
        marginBottom: 24,
    },
    chartContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-end",
        height: 180,
    },
    chartBarWrapper: {
        alignItems: "center",
        flex: 1,
    },
    barBackground: {
        width: 8,
        height: 120,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
        borderRadius: 4,
        justifyContent: "flex-end",
        marginBottom: 12,
    },
    barFill: {
        width: "100%",
        backgroundColor: Colors.dark.primary,
        borderRadius: 4,
    },
    chartDate: {
        color: Colors.dark.textSecondary,
        fontSize: 9,
        fontWeight: "600",
        transform: [{ rotate: "-45deg" }],
        marginTop: 4,
    },
    chartValue: {
        color: Colors.dark.primary,
        fontSize: 8,
        marginTop: 4,
        position: "absolute",
        top: -20,
    },
    infoBox: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(99, 102, 241, 0.05)",
        padding: 20,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "rgba(99, 102, 241, 0.15)",
    },
    infoText: {
        color: Colors.dark.textSecondary,
        fontSize: 13,
        flex: 1,
        lineHeight: 18,
    },
    emptyContainer: {
        flex: 1,
        backgroundColor: Colors.dark.background,
        justifyContent: "center",
        alignItems: "center",
        padding: 30,
    },
    emptyIconWrapper: {
        marginBottom: 40,
        alignItems: "center",
        justifyContent: "center",
    },
    emptyIconBg: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: "rgba(234, 179, 8, 0.1)",
        justifyContent: "center",
        alignItems: "center",
        zIndex: 2,
        borderWidth: 1,
        borderColor: "rgba(234, 179, 8, 0.2)",
    },
    pulseContainer: {
        position: "absolute",
        zIndex: 1,
    },
    pulse: {
        width: 160,
        height: 160,
        borderRadius: 80,
        backgroundColor: "rgba(234, 179, 8, 0.05)",
    },
    emptyTextWrapper: {
        alignItems: "center",
        marginBottom: 40,
    },
    emptyTitle: {
        fontSize: 24,
        fontWeight: "900",
        color: Colors.dark.text,
        marginBottom: 16,
        textAlign: "center",
    },
    emptyDesc: {
        fontSize: 15,
        color: Colors.dark.textSecondary,
        textAlign: "center",
        lineHeight: 24,
        paddingHorizontal: 10,
    },
    startNowButton: {
        backgroundColor: Colors.dark.primary,
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 16,
        paddingHorizontal: 32,
        borderRadius: 18,
    },
    startNowButtonPressed: {
        opacity: 0.8,
        transform: [{ scale: 0.98 }],
    },
    startNowText: {
        color: "#0F172A",
        fontSize: 16,
        fontWeight: "800",
    },
});
